package xyz.korayucar.algorithmstudy.floodingcity;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'koray' at '3/14/17 2:17 PM' with Gradle 2.8
 *
 * @author koray, @date 3/14/17 2:17 PM
 */
@FunctionalInterface
public interface FloodingCity {

    int getWaterCapacity(int[] city);

}
